### ISSUE TITLE
Intuitive item and track selection

### ISSUE THREAD

**Issue by Justinmac84** [nvaccess/osara#109]
Hi, 

Would it be possible to make item and track selection behave more as making selections does in other programs. I.e. if you press shift cursor down, you select contiguous tracks going one way but, if you have a block of tracks selected, if you press shift cursor up, you unselect the bottom track selected? Likewise with items and envelope points? 

Thanks, 

Justin

**Comment by jcsteh** [comment]
While I acknowledge this is closer to how it works in other apps and consistency is a good thing, I'm dubious about this idea for three reasons:

1. It doesn't quite make sense with respect to the way we do non-contiguous selection. Other apps have dedicated non-contiguous selection keys. We can't do that in REAPER because it would eat way too many keystrokes. So, we use shift+arrows for both purposes and switch modes.
2. It's contrary to how most selection actions work in REAPER. I'm certainly not against overriding some things REAPER does to make them more intuitive for keyboard users, but it seems to be a pattern in REAPER that actions which select next/previous always add to the selection; they never subtract from it.
3. Technically, this is kinda tricky to get right. It's not so hard to track when you're considering just those actions, but it gets very messy and error-prone when you consider other ways of manipulating the selection; e.g. select all items in current time selection. In this case, figuring out whether the selection expanded forwards or backwards is problematic.

I'm going to close this, though I'm happy to discuss it further if there are compelling arguments that outweigh these.
