### ISSUE TITLE
Implement context sensitivity and feedback for actions related to automation items (added in Reaper 5.50)

### ISSUE THREAD

**Issue by ScottChesworth** [nvaccess/osara#125]
As things stand, actions related to automation items don't seem to be integrated into Reaper's context sensitivity. Is this something that OSARA could take care of? We're imagining a UX whereby a user could navigate to an automation item using existing keystrokes to move through items on a track, then use existing keystrokes to select, duplicate, cut copy or paste them (as opposed to needing to find assignments for an entirely separate set of actions).

**Comment by jcsteh** [comment]
As far as I've been able to determine, copy, paste, etc. already respect automation items as things stand now. OSARA doesn't report this though because it doesn't know about automation items.

Navigation is a bit trickier. That's covered in the earlier issue you filed, but briefly, automation items and normal items are entirely separate. It's not going to be possible to have them appear when just navigating by item, not least because they are envelope specific. My current thinking is that when an envelope is focused, the item nav commands would navigate automation items instead of normal items. The only downside is that would mean you'd have to move away from the track and back again to start navigating normal items again. I personally think this is acceptable, but others may disagree, though disagreement would need to be accompanied by a reasonable alternative to navigate/select automation items that doesn't consume keystrokes we don't have room for. :)

**Comment by GianlucaApollaro** [comment]
By further playing with automation items I confirm what James said. I imagine something like select the envelope and then move to its automation items with current navigation keystrokes. I would also like to see their context menu working with applications key. One other thing I noticed is that when you have an  automation item you can't navigate between the envelope points within the item, but, when navigating between points, automation items seem to get selected.

**Comment by jcsteh** [comment]
Note that it's not currently possible to access the context menu for an automation item. This is going to need a change in REAPER. Alternatively, we could fake our own context menu which just contains the automation item actions accessible from the Actions dialog, but I'm not sure how useful this is given that there aren't that many of them.

I also can't seem to figure out how to insert an envelope point into an automation item. If you create an automation item, you can set things up so that the item absorbs the points. However, inserting a point (even with an automation item selected) always inserts it into the underlying envelope, not the automation item. It'd be good if someone could figure out how this is done even from a sighted user's perspective.

Anyway, any additional features/changes here should be filed as separate issues.
