### ISSUE TITLE
Provide context sensitive feedback for cut, copy and paste

### ISSUE THREAD

**Issue by cmdfv** [nvaccess/osara#23]
When copying/pasting currently with OSARA, there is no speech feedback.

More often than not, I'll be working in a project and try to cut an item or track and get unexpected results using the default copy/cut/paste behaviors. That plus no audible feedback, and it gets cripple pretty fast.

These OSARA cut/copy/paste actions should also be context sensitive. For example, I press downArrow to move to track5, and I want to cut it. When I press the keystroke to cut in OsARA, it should cut track5. 
When I then move through items on a given track and perform a cut or copy, OSARA should cut/copy the items, not the entire track.
The number of items/tracks should be spoken as well. "2 items copied" or "1 track cut," etc. 
Items/tracks should be spoken first, the action performed spoken last. More efficient.

**Comment by jcsteh** [comment]
Regarding context sensitivity, these already seem to be context 
sensitive for me with OSARA. If I move to a track and press control+x, 
it cuts the track. If I move to an item and press control+x, it cuts the 
item. I verify this using the undo description. Are you saying this 
isn't the case for you? I fixed context sensitivity for such commands in 
late February. As you say, we don't yet have action feedback.

**Comment by cmdfv** [comment]
With the right actions set up, I've managed to kill the flakyness with
it cutting random things instead of what I'm after. So yes, the only
thing now is action feedback. Sorry for confusion.

Alex

**Comment by jcsteh** [comment]
Providing feedback for cut and paste shouldn't be a problem. However, there's no way to be absolutely certain copy actually succeeded. You can assume it did if there were selected tracks or items, but there may be other required conditions I'm unaware of. Do you know if sighted users get any indication that copy actually occurred?

**Comment by ScottChesworth** [comment]
Alex, if you're not aware, i can get this verified tomorrow.

On 27 Mar 2015, at 01:15, jcsteh <notifications@github.com> wrote:

Providing feedback for cut and paste shouldn't be a problem. However,
there's no way to be absolutely certain copy actually succeeded. You can
assume it did if there were selected tracks or items, but there may be
other required conditions I'm unaware of. Do you know if sighted users get
any indication that copy actually occurred?

--
Reply to this email directly or view it on GitHub
<https://github.com/jcsteh/osara/issues/23#issuecomment-86782510>.

**Comment by ScottChesworth** [comment]
Just been researching this, and so far, I can't find any mention that sighted users get visual confirmation. I'll get a set of eyes to verify this later. Assuming they don't, this is a bit of a sticky wicket, because it'd be mega useful for us to know what's been done, but we wouldn't want OSARA to report false info. Is there any mileage in being a bit cheeky with it and speaking something like "5 items copied, hopefully"? That would provide info on what was selected when the user hit CTRL+C in line with the behaviour of cut and paste actions, and also serves as a reminder that OSARA can't be certain that it worked. I'm betting that anyone who's used to the workflow they're carrying out wouldn't wait around to get annoyed by the end of that message. Alternatively, perhaps it's a blessing that I'm not coding this thing :P

**Comment by cmdfv** [comment]
I'm not aware of anything visually, though it's probably just clicky
clicky for them. See what ya can find out.

**Comment by jcsteh** [comment]
Ug. Saying "hopefully" or something is... no. :)

If sighted users don't get confirmation, I'd rather not do this at all for copy. If we can't be certain it worked, we shouldn't be reporting it, and if sighted users don't get confirmation either, we're not at any disadvantage here. Sighted users can check the selection first, but OSARA users will get that eventually, too.

**Comment by ScottChesworth** [comment]
Fair point. Guess I was trying to avoid hitting that extra keystroke to check selection. Laziness is alive and well :)

**Comment by ScottChesworth** [comment]
Just got someone to check this. There's no visual indication to distinguish between a successful or unsuccessful attempt to copy tracks, items or takes so far as we could fathom.

**Comment by jcsteh** [comment]
I'm providing feedback for copy based on focus and what's selected. I can't actually *guarantee* that it was copied, but I guess there's no reason it shouldn't be. If this ever proves to be false, I will probably remove this functionality, since potentially incorrect reporting is an intolerable evil. :)

**Comment by ScottChesworth** [comment]
I reckon this issue needs to be reopened temporarily, as I've seen requests for OSARAs context sensitive action feedback to be extended to the piano roll if possible?

**Comment by jcsteh** [comment]
Please open another issue for this. Having this kind of feedback in the 
Piano Roll is not as simple as just extending the current functionality. 
We need to work out *what* to report; e.g. "5 events removed", "5 notes 
removed"... or what? Also, OSARA doesn't have any code for MIDI event stuff.
