### ISSUE TITLE
Reaper crashes on Osara fx parameter changing for Waves IR plugin

### ISSUE THREAD

**Issue by leonardder** [nvaccess/osara#39]
I'm using Waves IR for impulse responses. It has several parameters which can be changed using a somewhat accessible gui. Using the osara parameter list however, as soon as I change one of the parameters, the vst host process crashes. Is there a way to rule out whether this is an Osara bug or not?

**Comment by jcsteh** [comment]
Given that it doesn't happen for other plug-ins, it's unlikely to be an 
OSARA bug as such. More likely, the plug-in can't handle what OSARA is 
doing. For example, a host probably wouldn't normally query the value 
text for a value which isn't the current value, but OSARA has to do this 
in order to work out where the next useful value is.

I'd probably first test whether this works via MIDI learn or similar. 
It's unlikely to crash--surely they would have tested this--but if it 
does, that'd suggest automation is just broken.

Failing that, given that (I assume) I can't test this myself, I'd need a 
minidump from the crash. You'll probably need to use a debugger like 
WinDBG to do this. Do you have any experience with using a debugger? 
Otherwise, this isn't really feasible; it's not trivial.

**Comment by leonardder** [comment]
I'm afraid i don't have any debugging experience on Windows. Think i will just stick to using the somewhat accessible plugin gui than.

**Comment by jcsteh** [comment]
There may be a way to enable minidumps from Windows crash reports. See [this thread](http://superuser.com/questions/553140/where-does-windows-8-store-user-mode-crash-minidumps). I've not played with this, but if you can get it working, it's probably easier than using a debugger.
