### ISSUE TITLE
Little request about the new way of focusing master track

### ISSUE THREAD

**Issue by GianlucaApollaro** [nvaccess/osara#48]
Hi,
This is a request more than an issue. Is it possible to have the master track appear as the first one on the list, only when we make it visible?
So that we know exactly when we can focus it
Thanks

**Comment by ScottChesworth** [comment]
This would be in line with the ux for sighted folks yeah.

On 14 Nov 2015, at 21:17, GianlucaApollaro <notifications@github.com> wrote:

Hi,
This is a request more than an issue. Is it possible to have the master
track appear as the first one on the list, only when we make it visible?
So that we know exactly when we can focus it
Thanks

—
Reply to this email directly or view it on GitHub
<https://github.com/nvaccess/osara/issues/48>.
