### ISSUE TITLE
Track: Changing track status with tab and checkboxes

### ISSUE THREAD

**Issue by SchockMock** [nvaccess/osara#5]
In Reaaccess, it is possible to navigate to a track and changing track Parameters with check boxes by pressing tab.
For example parameters like solo, mute, pan, vol, record...
But if i press the tab key, OSARA don't jump to this area.

**Comment by Michael1972** [comment]
This would make the tab to transient with the tab-key impossible. But that's a very useful feature for editing.

**Comment by chrisbelle2015** [comment]
No way, that tab to transience is the way it should be.

Don't change that.

**Comment by chrisbelle2015** [comment]
I've been using a couple of hotkeys and some sws things to get to item 
and track editing parameters,
but it would be nice to have an easy way to get to the most commonly 
used parms, not stealing the tab key,
like for instance we used to could go in to reaccess and see where 
things were set, but now you have to go in to item properties
and use object nav,
doable, but not easy to quickly tell where you set pan or volume for 
items when you are splitting up a lot of things and editing.

I don't know what the perfect answer is for this,
but knowing say I've got 3 db up on an item, or 4 db down from 0,
would be handy to quickly tell.

**Comment by jcsteh** [comment]
I've just uploaded a new build which adds parameter list dialogs for tracks and items. Right now, only very few parameters are exposed, but I'd love some initial feedback.

Obviously, this is quite different to the way ReaAccess does it. It uses a dialog like the FX Parameter List rather than the tab key or similar. The advantages are that it doesn't use the tab key, parameter lists are consistent and you can jump to parameters by typing the first letter of the parameter name. It will also benefit from any future changes to the Parameter List dialog such as the ability to filter the list or type text as the value for parameters which support it.

**Comment by chrisbelle2015** [comment]
Niced Jamie.

My only comment is that I noticed that down goes up and up goes down on 
the volume parameter.
with arrow keys, and same for page up and down keys

Also when using page up and down keys, we jump by huge amounts like all 
the way down, and  then back to a value we might have set with the arrow 
keys.

  On the pan and the mute, things are working in a consistant and 
expected manner.

Thanks for all you do.

**Comment by MatejGolian** [comment]
Does it also work for the master track?

2015-09-25 11:44 GMT+02:00, chrisbelle2015 <notifications@github.com>:

**Comment by jcsteh** [comment]
> Also when using page up and down keys, we jump by huge amounts like all the way down, and  then back to a value we might have set with the arrow keys.

Can you clarify that second bit? I know the jumps are big, but I don't get the "and  then back to a value we might have set with the arrow keys" bit. Maybe an example?

> Does it also work for the master track?

Not yet, but I plan to make the master track focusable, at which point you'll be able to do this. I guess this could be a separate action if people really want one.

The other question is what parameters people want in here. I don't want to put in the entire kitchen sink just for the sake of it. For example, some parameters like input and output channel are very quickly and easily accessed via context menus and it seems redundant to include them here. That said, I'm very happy to add any parameters people genuinely think would be useful.

**Comment by chrisbelle2015** [comment]
Ok let's see, when I used the arrow keys to press upwards a few times to 
bring the volume down to say -1.8db, then used the page-up it would jump 
from that -1.8 down to -60 or -inf.

Then when I press page down to bring it back up, instead of jumping up 
in increments it would jump back to that -1.8 value.

So no continuity or linearity with the volume changes.
Pan seems to work more as expected.

As far as adding lots of controls to the dialogue goes, my thought is 
that for beginners, this would be an easy way to find the most needed 
things.

People seem to like that fake dialogue,
that was in reaccess,
which for me was sometimes handy,sometimes annoying depending on what I 
was doing, but consider it like the track properties dialogue in sonar.
just another way to do things.

It doesn't bother me to have more than one way to do things,
but  I know how you are about program bloat and keeping things in scope, so
for me it's like ok, I'm as lazy as the next guy, nice if they were all 
in there, but if they're not I won't throw a fit.

I think if you followed the reaccess model, you'd probably make most 
people happy,
that were used to that,
but let's see what others think.

**Comment by jcsteh** [comment]
> Ok let's see, when I used the arrow keys to press upwards a few times to bring the volume down to say -1.8db, then used the page-up it would jump from that -1.8 down to -60 or -inf.
Hmm. Yeah; the problem is that volume isn't internally linear or evenly distributed. There are a lot more values below 0dB than above. I'll need to play with this a bit.

I don't have a major objection to adding all of the parameters if people really use them, but it just seems that learning the context menus is pretty important. We shouldn't expect users to necessarily fiddle in the routing dialog or the Item Properties dialog, but context menus are pretty simple and basic. Also, adding too many parameters might actually be more confronting because you have to scroll through a massive list.

**Comment by chrisbelle2015** [comment]
I agree.

**Comment by jcsteh** [comment]
The major functionality is now implemented. I've added a few parameters that were requested, but haven't had more feedback than that. Please file new issues for additional desired parameters.
