### ISSUE TITLE
Peak watcher: add slider to control hold peaks value

### ISSUE THREAD

**Issue by ScottChesworth** [nvaccess/osara#63]
I've heard a few comments along the lines that the hold peaks ms value being a range from -1 to 0 specified in an edit field is less intuitive to some people. Should a slider to specify this be added, with nice user friendly values like "don't hold" and "hold until reset" at either end?

**Comment by jcsteh** [comment]
Aside from hold until reset, What maximum time would you suggest? Also, 
what increment on the slider? The trouble with sliders is that they can 
be more fiddly when you have a specific value in mind. I get around this 
in the Parameters dialog by having an edit field as well, but I'm 
reluctant to have both an edit field and a slider in this case.

**Comment by ScottChesworth** [comment]
I can't really imagine why anyone would want to hold peaks for more
than say 20 seconds instead of just using hold until reset, so perhaps
that should be the max. I'd suggest half second intervals on the
slider assuming that we were to keep the edit field too. Why the
reluctance to have both in this case?

**Comment by jcsteh** [comment]
I'm reluctant to keep the edit field for several reasons:

1. It makes that dialog even more complicated.
2. If people are really confused by the -1 and 0 values, that's still going to hold if they see those values after manipulating the slider. You can't assume people will ignore the edit field just because there's a slider.
3. It is also a lot more complicated in terms of code.

Does the 0 confuse people or just the -1? If it's just the -1, we could just have a check box for "Hold until reset" which disables the edit field.

**Comment by ScottChesworth** [comment]
So far as I've been able to tell, the zero and minus 1 are both
confusing people. I'm not opposed to losing the edit field really
having thought about it, can't think of any scenarios where absolute
precision of how long a meter holds for would ruin my day. A slider
and your checkbox override suggestion sounds like a much neater UX to
me.

**Comment by jcsteh** [comment]
If we have a slider and no edit field, we don't need a check box. 
Unfortunately, implementing that is a lot harder than it sounds. :)

**Comment by ScottChesworth** [comment]
Is an edit field with a check box override as you described earlier
any easier to put together? It'd still go some way toward making
things easier for people to understand I think.

**Comment by jcsteh** [comment]
Significantly easier, I think. Let me see what I can come up with.

**Comment by chrisbelle2015** [comment]
Just for my vote, I was not confused by the peak watcher at all.
I am quite used to it now.
But if it's really a big deal to others, I can adapt.

**Comment by chrisbelle2015** [comment]
I like being able to just type in a value, and have done with it.

**Comment by jcsteh** [comment]
On further thought, do we actually need a "don't hold" value at all? I added that because we didn't have actions to report the current meter level for the current/master track, but once those get added, having the Peak Watcher support this seems redundant. "Don't hold" is then just the same as current meter level.

**Comment by ScottChesworth** [comment]
Peak watcher automagically alerts you when a specific db level is reached though. I wasn't imagining that reading the current level would do the same thing. Perhaps renaming don't hold to something like alert only would clear this up?

**Comment by jcsteh** [comment]
Ah, so you don't care about reading the Peak Watcher value on-demand in 
this case, but you do want it to keep alerting you even if it hits the 
alert threshold over and over again. For example, if the threshold is -6 
and the audio hits -3, quickly drops to -10 and quickly rises again to 
-4, you want to be alerted twice. Is that correct?

**Comment by ScottChesworth** [comment]
Yep, that's it in a nutshell.
