### ISSUE TITLE
Request for additional actions and feedback related to metering

### ISSUE THREAD

**Issue by ScottChesworth** [nvaccess/osara#69]
The below came from a discussion between Justin, Derek, and a few others on the Cavi OSARA short course. It's kinda lengthy, but Justin does a solid job of describing the UX benefits, so I've pretty much left it as is.

Firstly, would it be possible to incorporate a means to simultaneously monitor instantaneous levels as well as peaks? At present, it is only possible to do one or the other. Having this feature would give vision impaired users an idea of the RMS level of their audio, albeit only a rudimentary one, while simultaneously enabling them to monitor peak levels. This would be particularly useful for determining the dynamic range of audio and ascertaining the level of a noise floor for setting noise gates etc.

It would also be useful to have an action to read each channel to speed up work-flow. A sighted person may look straight away at the channel he/she is interested in, whereas, with the current setup, if we are interested in the right channel at a particular moment, we must first listen to unnecessary information. Particularly when hold is set to -1, or if a feature such as the one described above were to be implemented, this greatly reduces the amount of useful information a vision impaired person can access in close to real time.

It would also be useful to be able to follow the master track at the same time as another track to identify clipping at the master early. If one is building a project track by track using the current setup, adding effects and so on, with the current track soloed, there would be no way to know when you pushed the overall project level too high until either you came to look at the master with all tracks unsoloed at the end, by which time it would be difficult to work out which track was the problem, or by auditioning each track twice, once following the master and once following the current track, which would be time-consuming.

Another instance where it would be helpful to be able to follow two tracks at once would be to identify clipping caused by phase issues. Following each track independently, all levels may look fine, but if an odd phase relationship between two tracks causes clipping when they're added together, this would be hard to identify.

In brief, here are a list of actions that'd be super useful:
Say current   peak for channel 1
say  current peak for channel 2
Say current   peak for channel 1 of master track
say  current peak for channel 2 of master track
Say value of peak inspector for channel 1
Say value of peak inspector for channel 2
Reset peak inspector for track
Reset peak inspector for master

Thoughts?

**Comment by jcsteh** [comment]
Thanks for the explanations. I've seen mumblings about stuff like this, but no one has ever been able to explain the use cases. Some issues and questions below:

> Firstly, would it be possible to incorporate a means to simultaneously monitor instantaneous levels as well as peaks?

It's certainly possible. The only problem is that this means we have even more actions to find keystrokes for, which is why I didn't do it in the first place. When it comes to designing the final key map, we're going to have to think very carefully about what goes in by default and what people bind themselves for their own workflows.

> It would also be useful to be able to follow the master track at the same time as another track to identify clipping at the master early.

I have two concerns here:

1. I believe ReaAccess did this by way of a "With master" check box, which IMO is a pretty horrible UX; it doesn't make a huge amount of sense unless you try it, particularly because you can also select master in the list of tracks.
2. Would you also want additional actions to read the peak watcher value for master? See above re too many actions.

> If one is building a project track by track using the current setup, adding effects and so on, with the current track soloed, there would be no way to know when you pushed the overall project level too high

Wait. So the master still shows the level for all other tracks even when you solo a single track? I would have thought master would only show output from the current track, since all other tracks aren't playing. Or am I misunderstanding this?

> Another instance where it would be helpful to be able to follow two tracks at once would be to identify clipping caused by phase issues. Following each track independently, all levels may look fine, but if an odd phase relationship between two tracks causes clipping when they're added together, this would be hard to identify.

Again, we need to work out the UX:

1. How would the user select multiple (normal) tracks? I'm starting to think a list of check boxes or something will work best, though I'm actually not sure I can implement that in the time we have.
2. How would you report the peaks on demand for these additional tracks? I honestly can't think of a sane way to do this. Actions like "Report peak watcher value for channel 1 of the second selected track" seem a bit insane. And assuming we didn't care, which track would the on-demand actions report? You can't just say the first because the tracks will be in order and the user might actually be more interested in one of the tracks further down.

**Comment by chrisbelle2015** [comment]
Not everyone is going to use all the actions which are useful to 
everyone in different senarios, so having useful actions like this won't 
consume keystrokes will they unless you bind them?
There's just no way to have easy access to everything as reaaper is just 
too vast.
I like all these commands,
and I can imagine me using them at a given time, but let's don't overly 
complicate the peak watcher dialogue.
Is it really that hard to understand -1 disable, don't hold peaks, and 0 
hold them forever?
I guess having a slider and an edit box together with one extreme being 
hold forever and the other being
don't hold, disable would be ok,
but then you have to have some reasonable limit on the range,
now you can type in what ever value you want.
I can give a use senario to have peaks holding a long time.
If I am doing a very long book or something where I am looking for a big 
peak,
and I don't want it to change, and I forget what my last peak was, it's 
nice to still have it there.
Of course, one can always test it as you go, but if it's still there, 
and doesn't change to a higher value, you know that.
as you seek.
Normally I set this to 2000
2 seconds is my usual working range, but it's so easy just to jump in 
there, and type in a value.
But as stated in my other email, if others really want to change this, I 
can adapt, but i think it's the most useful the way it is.
Because you have an infinite range, even if you won't always use it,
it's there.
Something about infinite ranges appeals to me.
'grin'.

**Comment by Justinmac84** [comment]
I've done some research, particularly in relation to what the master shows when tracks are soloed and have discovered I'm kind of right but not completely. 

you're right Jamie in that the master track only shows level information based on the audio that is coming across it from your soloed track. However, Rea Access would follow the master in addition to whatever the last touched track was, regardless of whether it was soloed or unsoloed. so you could have track 1 soloed, follow track 2 and the master and hear if track 2 clipped, which isn't particularly useful. 

So my use case wasn't particularly sound, but there are others where being able to follow the master as well as whatever track you are touching would still be useful and I'm sure that sighted people have that opportunity.

Say all tracks are unsoloed and you want to apply a level boosting effect to a track, it would be helpful to know right away if the change clips the master as well as the track you're working on. As for too many keys being taken up, the function row is pretty clear at the moment and people can bind keys as they please. It's having the actions available for people to bind, having the potential to access the information that's the important thing. 

In response to Chris, I agree, being able to change the hold time is an excellent bonus, but what if I want to know not only the highest level my whole track reaches, but where the track is sitting at a given point at the same time, both to have a rough idea of RMS and also, as I say, to set noise gates etc. With the current system, I would have to conduct two passes, one to set the noise gate, the other to determine the highest peek of the whole track. Were there actions to read current level of desired channel and peek level of  channel with an indefinite hold time simultaneously, this would have all kinds of benefits. 

Another use case would be micing someone. 

You get your vocalist to sing into the mic and you want to see what his/her highest peek is. As you're bringing his/er level up, you also want to get a picture of what that's doing to your noise floor to strike the best compromise. A sighted person can look at the screen and take all this in at a glance, whereas, with the current setup, we would have to go in and out, in and out of the peekwatcher dialogue, which is why a reset action would also be highly useful. 

I agree that implementing the ability to follow any two given tracks at once may be difficult. It would be good to have, but being able to follow the master and one other track would be the priority for me by far. 

If it should prove doable however, I would have speech report m1 and m2 whenever the master exceeded the designated level. If you were following two tracks that weren't the master, I would have speech say 1l for the first track in chronological order and 1r, 2l and 2r, for first track right and second track left and right if that makes sense.

**Comment by jcsteh** [comment]
> As for too many keys being taken up, the function row is pretty clear at the moment and people can bind keys as they please. It's having the actions available for people to bind, having the potential to access the information that's the important thing.

I'd love to agree with you, but it's far from that simple. There is still a need to come up with a default key map that is intuitive for the majority of users. Personally, I'd prefer not to have a default key map at all, as it completely avoids this issue, but that view is unpopular among users.

> actions to read master and at least one other track's peeks at the same time, channel by channel, would be extremely useful, also to be able to read master's current level and another tracks level at the same time.

You're being vague by saying "another track". Which one? The current track or the track being monitored? And what if you're monitoring two tracks at once? Which track then? And that's only one set of actions, since you want two sets: one for the peak watcher level and one for the current meter level. So the same questions then apply to the other set of actions.

To make matters worse, REAPER allows more than two channels per track. Do we need to support channels beyond 2? And if we do, how many? ReaAccess did 4, but 4 seems kind of arbitrary to me.

The UX needs to be clearly defined here. I've made my case for this whole thing being counter-intuitive, but what I've implemented so far clearly isn't sufficient for some. So, give me a specific, down-to-the-letter idea of the UX you're proposing. Any vagueness whatsoever just isn't acceptable when you're trying to define requirements. Thanks.

**Comment by chrisbelle2015** [comment]
I think the relative following of the old reaccess
key map that Osara has taken is pretty cool,
the work that Derick and Gn luca have done in this regard most of us are 
happy with.
It's easy enough to change anything we don't like.
But it's nice to have a starting place.

**Comment by Justinmac84** [comment]
Hi,

I don't know how difficult this would be but if you implemented 
multi-presses for determining more than two channels, this should be 
neat, tidy and compact.

I would propose, if we're going for best case scenario:

Alt f9 press once, say peek for channel 1 of first selected track.
Alt F9 pressed twice or thrice, say peek for channels 3 and 5 
respectively, four times potentially for 7. I can't see that we need to 
go higher than that because mixes are seldom more than 7.1

Same deal for alt F10 for channels 2, 4, 6 and 8.

Alt F11 and F12 would do the second selected track, first and second to 
be dictated by where they come in the track order, as opposed to the 
order in which user last touched or selected the tracks.

Alt shift F9 to say peek for master left channels in the same way and 
alt shift f10 likewise.

Alt shift F8 to reset the peekwatcher.

Likewise we would need actions to do the same for instantaneous level 
watching. Shift J and K have been taken by other functions in Derek and 
co's keymap, which seems to be the default for most users. I've started 
to use windows key plus shift as a modifier because of running out of 
actions, although, with the master track focussable now, we could 
potentially do away with some bindings on the keymap, if not the actions 
themselves.

I'm about to go out but will catch up with Chris' message, which I 
haven't had chance to read yet, tonight.

I hope this is helpful and sorry to be a pain.

One thing that Scott, quite understandably, didn't feel at liberty to 
pass on from our discussions, is that I and others would like to know if 
there is a way to donate to this project. I would be more than happy to 
do so,

Justin

**Comment by Justinmac84** [comment]
Just as a brief adendum, if it could be set such that, if you are only 
following one track and the master, if you have the peekwatcher set to 
last followed track with master I mean, if that could show as first 
selected track in my previous example, that would be good I think.

Right that was worded terribly let's try again.

Say you only want to monitor one track, last touched for example, as 
defined in the combo box we have now, if alt f9 and f10 would work 
there, as well as working for the track that comes first chronologically 
out of a pair of tracks being followed together that aren't the master, 
I think that would work.

Justin

**Comment by jcsteh** [comment]
Thanks for the additional info.

If I understand your last comment correctly, you're saying that the commands which report the values for the first selected track should report the master if there's only the master plus one other track selected. IMO, that's counter-intuitive, since it will sometimes report a track and will other times report the master. Also, that means we're unnecessarily wasting dedicated keys for the master.

Could we not just allow two tracks to be selected (where the master could be one of those tracks)? That way, you can either use those keys for two tracks or the master and one other track. Surely, the master plus two other tracks is getting a bit crazy.

Finally, all of these actions relate to the peak watcher level. Regarding the current meter level, I'm thinking those commands should just be for the current track and the master track, since they have nothing whatsoever to do with the peak watcher. That is, they'll work even if the peak watcher isn't even activated. Sound fair? I believe ReaAccess does the same.

Regarding donations, you can [donate to NV Access](http://www.nvaccess.org/donate/). Thank you!

**Comment by Justinmac84** [comment]
Hi,

I was saying that the first selected track action should double as the 
one that wasn't the master if the master and only one other track were 
selected.

I'm wondering if there are some applications with sends that might 
benefit from being able to follow three tracks at once, esp where send 
to parent is involved for vocoding and things.

I am far too mushy-headed at the moment to think of a working example 
though and those cases would be few if it would mean a lot of extra work.

Yes I think it would be great to have the instantaneous level metering 
available whether or not the peekwatcher was enabled.

Given that multi-press wouldn't work with this latter function for 
obvious reasons, I can see the logic to restricting it to two channels 
of followed track plus master.

I don't work with greater than two-channel audio so this wouldn't bother 
me.

Justin
