### ISSUE TITLE
copy the bundled keymap from the Osara installation to desired location for easier merging with existing keymap

### ISSUE THREAD

**Issue by chrisbelle2015** [nvaccess/osara#80]
Though one can unzip the installation file, and grab the keymap, this is cumbersome, so we need a way to get the keymap bundled with Osara so we can merge to an existing keymap rather than just over-write or have to export our own custom actions and re-import them after having imported the factory keymap.

**Comment by jcsteh** [comment]
I really don't want to pop up a dialog asking where to extract it; that's just ugly. It would make sense to extract it to the KeyMaps directory in your REAPER config, since that's where other key maps go. However, it seems that on my system, my installed copy of REAPER doesn't always look there by default. How about yours?

**Comment by chrisbelle2015** [comment]
What is the name I should look for,
remember, I'm running a portable copy but I did look in the users folder 
just in case, and I didn't see anything new.
In other words, there wasn't a reaper folder made in the users folder 
which usually happens when an installed copy of reaper is done.
I looked in the keymap folder in my portable copy and it all looked the 
same, no new stuff in there.

**Comment by jcsteh** [comment]
Mm, I haven't made the change yet. I mean, when you go to import a key 
map, what folder does REAPER's import dialog initially place you in?
