### ISSUE TITLE
action feedback for item lock state

### ISSUE THREAD

**Issue by ScottChesworth** [nvaccess/osara#86]
When navigating to an item, it would be useful if OSARA notified the user if the item is locked.

**Comment by chrisbelle2015** [comment]
Can I ask a dumb question,k what is a locked item?
Common sense says it's one that won't move on the time line,
is that correct?

**Comment by MatejGolian** [comment]
You are correct, Chris, but locking items so that they can not move is
only one possibility. For example you can also lock the time
selection. Go to Options > Locking > Locking settings to see what else
locking can be used for.<div
id="DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2"><br />
<table style="border-top: 1px solid #aaabb6;">
	<tr>
		
		<td style="width: 470px; padding-top: 20px; color: #41424e;
font-size: 13px; font-family: Arial, Helvetica, sans-serif;
line-height: 18px;">Tento email byl odeslán z počítače bez virů,
chráněného programem Avast. <br /><a
href="https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail"
target="_blank" style="color: #4453ea;">www.avast.com</a> 		</td>
	</tr>
</table>
<a href="#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2" width="1" height="1"></a></div>

2016-03-10 16:34 GMT+01:00, chrisbelle2015 <notifications@github.com>:

**Comment by chrisbelle2015** [comment]
Cool, will explore, and thanks.
