### ISSUE TITLE
step sequencer support reaper

### ISSUE THREAD

**Issue by ececrios907** [nvaccess/osara#90]
would like osara to support REAPER's JS step sequencer called megababy

**Comment by jcsteh** [comment]
It's probably not possible for OSARA to make this accessible. At the 
very least, I'm going to need information about how this works for a 
sighted user, or better still, how it works for a sighted user doing it 
without the mouse.

**Comment by ececrios907** [comment]
Hello Jaimie,
Thank you for considering this issue. I understand if you are unable to adapt osara for this particular request. I also want to thank you for given a lot of us sonar users a viable alternative. For that reason, I have donated once and plan to donate more frequently. Justin’s business philosophy may be to our advantage here as well.

On with the issue at hand.
I'm not sure on using it without a mouse yet, but I found a link to a brief tutorial on the JS mega baby sequencer for the sighted folks, which is easy to follow because audio is included.

http://www.untidymusic.com/wordpress/reaper-tutorials/creating-drums-in-reaper-sequencer-megababy

Note: I use the step sequencer built in with sonar 8.5, which CT supports, so I am aware on how it works and can work for us blind folks. I’m not sure if JSonar supported it though. 
From briefly reading the REAPER tutorial, it seems similar to the sonar step sequencer because it uses a grid-like structure. Of course, sonar does have fancy paint tools and brushes, but that is not used with the scripts. The only thing I didn’t see mentioned was the ability to tie notes together to extend lengths.
Sorry for the long note, but if you would like more info on how a step sequencer works, from a blind perspective, I would be more than glad to give you more info. I may be able to copy the CT tutorial on the step sequencer section so you can have an idea on how it worked under CT. There are also velocity controls involved. 
Lastly, I will try to get sighted assistance this weekend to further evaluate how it works in reaper.
Thanks for all your hard work!!!

**Comment by chrisbelle2015** [comment]
Likewise Jamie, all your hard work so much appreciated,
and it's encouraging to be getting reaper students as well.
I have a question, if need will put separate issue, but I have a student 
who can't get Osara to work on xp.

I suspect it's an Osara issue because the error asks for the resources 
directory and some bitmap file, my student isn't very technical, and I 
don't hve access to her computer remotely because it's of line.
i could probably hack around it and make it work, put files where they 
need to be,
I tried both the portable and standard installs, but it hangs up at that 
error message.
I need to test here on my remaining xp machine and see if it still does 
the same thing,
come to think of it I actually hve reaper running on my burner box which 
runs xp and it works fine, so maybe there's something else going on on 
her machine.
Maybe I am reporting prematurely,
but what got my atention was the resources directory mentioned, and I 
think the version on the xp box was before you implemented the install 
when we just dumped the dll in the plugins folder.
maybe if i do that it'll al work fine.
Maybe xp looses a link of some kind doing it the new way, who knows.
Cheers.

**Comment by jcsteh** [comment]
With respect, Chris, this isn't at all related to this issue. The whole 
point of issues is to keep discussion for an issue associated with that 
issue. Please post on a separate thread, probably on RWP. Thanks.

FWIW, OSARA doesn't have anything other than the dll and key map, so 
there's no resources folder. Also, I tested this on XP and it worked 
fine, so I'd say you're dealing with a problem with another plug-in.

I'm now removing both of these comments from this issue.

**Comment by GianlucaApollaro** [comment]
Hi,
Have you tried the step recording built in the piano roll of the midi editor? If so, what don't you lieke about it?

**Comment by ececrios907** [comment]
Oh. Ok. I'm new to reaper, so still learning all it has to offer. I didn't know the piano row step recording function was accessible. Will check that out and will let you know if it is what I am looking to accomplish.

**Comment by ececrios907** [comment]
Hello. I should have commented earlier, but no need for this request since the piano roll step sequencer is accessible and fulfills my needs.
